### ISSUE TITLE
Credentials should be sent in the headers

### ISSUE THREAD

**Issue by kmdm** [pfaffman/discourse-settings-uploader#1]
Just tried to use this but I had to update the script to send the credentials in the header instead of the request body: 

```
r = RestClient.put(url, my_hash, :'API-Username' => API_USERNAME, :'API-Key' => API_KEY)
```

(I also removed them from `my_hash`)

**Comment by pfaffman** [comment]
Thanks for the heads up! I guess nobody has used this in quite a while.

But the documentation was good enough that I was able to figure out how to use it! :-)
